[Feature] Github 인증 API 구현
woowa-techcamp-2022/web-fleemarket-05 pull request #26
Opened 2022-08-20 10:52 UTC by Hyeondoonge

## 💬 세부사항
Github 인증 API 구현
- 이미 가입된 사용자에 대해 woowa market의 access token 전달
- 새로운 사용자에 대해 DB에 email, github username값과 함께 user 등록
- 관련해서 발생할 수 있는 에러 핸들링

## 😭 어려웠던 점 또는 참고 사항
- 간단해보여서 빨리할 줄 알았는데 고민하는 시간이 많았어서 조금 늦어진 것 같아요.
  
[고민](https://www.notion.so/sangrimlee/7bc4bdf039f64614a5f9ac8e124cf26d) 
- github 관련 로직들이 전부 auth에 있어서 oauth 폴더를 하나 만들어서 거기다가 작성해야하는게 더 나은지 고민이에요.
- 에러 핸들링, 리팩토링을 추가적으로 진행하다가 시간이 많이 걸렸네요. ㅠㅠ

## ⏰ 실제 소요 시간
2시간

## 📎 관련 이슈

close #19

2022-08-20 11:57 UTC, sangrimlee requested changes
처음해보시는거라 많은 어려움이 있었을 거라고 예상이되는데 정말 잘하신 것 같아요👏🏼 

환경 변수만 잘 ConfigModule로 관리하는 로직과 Validation을 추가하면 좋을 것 같아요.

그리고, 고민한 것에 대한 제 의견을 알려드리자면, 그냥 email은 어떠한 값으로 사용하고, provider에서 제공해주는 고유한 ID로 관리하는 것이 좋아보입니다.

만약, Github로 로그인한 동일한 이메일로 이메일 사용자로 회원가입을 하려한다면, 이미 가입한 사용자라고 알려줄 것 같아요.

통합 로그인이나, 이메일 사용자에 연결해준다던지 많은 방법이 있다는 것을 알고는 있지만, 저희가 고민했다는 것에 의의를 두고 문서화를 해두면 좋을 것 같아요.

그리고, 가장 관리하기 쉬운 형태로 구현을 해보는게 좋을 것같아요. 다른 로직들을 생각해야될게 정말 많은 것 같아요😢

2022-08-20 11:57 UTC, sangrimlee commented on server/src/auth/auth.controller.ts
> +    };
여기서 해당하는 Github URL을 값으로 Response해주고 Client에서 window.location.href로 처리해주는 것 보다, 밑에서 처럼 Redirect로 처리해 주는게 좋을 것 같아요.

2022-08-20 11:57 UTC, sangrimlee commented on server/src/auth/auth.controller.ts
> +    console.log(github_user);
console.log 발견 ⚠️

2022-08-20 11:57 UTC, sangrimlee commented on server/src/auth/auth.controller.ts
> +    const githubLoginUrl = `https://github.com/login/oauth/authorize?client_id=${process.env.CLIENT_ID}&redirect_uri=${process.env.REDIRECT_URL}&scope=user`;
process.env.CLIENT_ID로 관리하는 것보다는 저희 ConfigModule으로 이제까지는 전부 관리했는데 그런식으로 ConfigService를 주입해서 configService.get<string>("CLIENT_ID")로 사용하면 좋을 것 같아요.

Valdation도 추가하면 좋은 것 같구요.
그리고 GITHUB_CLIENT_ID 이런 식으로 이름을 변경해줘도 좋을 것 같아요.
나중에 KAKAO나 NAVER, GOOGLE 이런것들이 생길수도 있으니깐요 😄

2022-08-20 11:57 UTC, sangrimlee commented on server/src/auth/auth.controller.ts
> +  @Redirect('http://localhost:4000', 301)
Redirect URL을 `/`로 처리하는게 좋아요.
아니면 나중에 배포할때는 다른 URL이라서 제대로 적용이 안될 것 같아요.

2022-08-20 11:57 UTC, sangrimlee commented on client/src/App.tsx
> +          const res = await fetch('http://localhost:4000/api/auth/github');
AuthController가 Redriect해주게 되면 사실 그냥 /api/auth/github/sign-in-url로 페이지를 이동하면 될 것 같아요.  a태그로

그리고 localhost:4000은 빼셔도 되요 자동적으로 /api로 들어가는 요청은 proxy로 localhost:4000번으로 변경하도록 webpack에서 같이 설정을 했었거든요!

그리고 URL도 잘못된 것 같아요.

2022-08-20 11:57 UTC, sangrimlee commented on server/src/auth/auth.service.ts
> +      `https://github.com/login/oauth/access_token?client_id=9a6d932339872c7d1117&code=${code}&client_secret=a3ba57be2e52b3ac8712b3c8e9f2493845f34672`,
위에서처럼 ConfigService를 한 번 써보는게 좋을 것 같아요.

2022-08-20 11:57 UTC, sangrimlee commented on server/src/auth/auth.service.ts
> +      const response = await fetch(`https://api.github.com/user`, {
fetch는 Web API여서 NodeJS에서는 사용이 안되는 걸로 알고있었어요. 사용하신걸보고 이게 왜 되는거지? 하고 찾아보니깐 최근부터 지원하기는 하더라구요.
하지만, 아직 LTS 버전인 v16에서는 experimental 단계라서 다른 서브라이브러리를 사용하는 편이 좋을 것 같아요.
그래서 axios나 got나 undici 또는 NestJS에서 제공하는 Module처럼 쓸 수 있는 @nestjs/axios와 같은 것들이 잘 나와있습니다.
한 번 찾아보시면 도움이 될 것 같아요.


**Reference**
[Node Release v16.15.0](https://nodejs.org/fa/blog/release/v16.15.0/)
[NestJS Http Module](https://docs.nestjs.com/techniques/http-module)

2022-08-20 11:57 UTC, sangrimlee commented on server/src/auth/auth.module.ts
> +    forwardRef(() => UsersModule),
저도 고민이 되네요. 순환참조를 이런식으로 처리를 해도 되는지?
두 가지 방법이 있을 것 같아요.
1. 순환참조를 forwardRef로 처리하고, 사용자 관련된 모든 서비스로직은 UsersService에서 처리하기
2. 순환참조를 허용안하고 사용자 + 인증 관련 로직은 AuthService에서 자체적으로 관리하기.

저는 1번이 더 좋다고 생각되는데 그렇다면 UsersRepository를 AuthModule에 주입하지말고, UsersService로 다 분리시키는 것도 좋아보입니다.

2022-08-20 11:57 UTC, sangrimlee commented on server/src/auth/auth.controller.ts
> +      url: githubLoginUrl,
URL을 Response로 주지말고 자체적으로 res.redirect(url)로 Redirect 해주면 더 좋을 것 같아요.

2022-08-20 12:00 UTC, sangrimlee commented
추가적으로 oauth의 모듈을 만들면 좋을 것 같다는 생각에는 저도 동의합니다! oauth 모듈은 나중에 리팩터링하면서 분리해보면 좋을 것 같아요.

2022-08-20 12:13 UTC, Hyeondoonge commented on server/src/auth/auth.controller.ts
> +  @Redirect('http://localhost:4000', 301)
넵!!

2022-08-20 12:16 UTC, Hyeondoonge commented on server/src/auth/auth.controller.ts
> +    console.log(github_user);
처리 완료!

2022-08-20 12:53 UTC, Hyeondoonge commented on client/src/App.tsx
> +          const res = await fetch('http://localhost:4000/api/auth/github');
넵 수정했습니다 :)

아래처럼 리다이렉트하도록 변경을 해줬는데, configService를 접근하자니 this가 undefined일 수도 있어서this as any를 사용해서 어찌저찌해결했는데 더 좋은 방법있을까요? ㅠㅠ

``` javascript
@Redirect(
    `https://github.com/login/oauth/authorize?client_id=${(this as any).CLIENT_ID}&redirect_uri=${
      (this as any).REDIRECT_URL
    }&scope=user`,
    301
  )
```

2022-08-20 12:56 UTC, Hyeondoonge commented on server/src/auth/auth.service.ts
> +      const response = await fetch(`https://api.github.com/user`, {
좋아요! 찾아보고 다음 기능 작업할 때 적용해볼게요 :)

2022-08-20 13:01 UTC, Hyeondoonge commented on server/src/auth/auth.controller.ts
> +    const githubLoginUrl = `https://github.com/login/oauth/authorize?client_id=${process.env.CLIENT_ID}&redirect_uri=${process.env.REDIRECT_URL}&scope=user`;
넷 반영했습니다!!

2022-08-20 13:08 UTC, Hyeondoonge commented on server/src/auth/auth.controller.ts
> +    };
좋은 방법인 것 같아요! 프론트엔드 & 백엔드 코드가 훨씬 깔끔해졌네요. 반영했습니다 :)

2022-08-20 13:17 UTC, Hyeondoonge commented on server/src/auth/auth.module.ts
> +    forwardRef(() => UsersModule),
1번 방식 처럼 순환참조를 허용하되, user관련 로직들은 모두 user 서비스로서 있게해서
서로의 서비스만 사용할 수 있도록 해도되겠네요!
바로 반영할게요~~

2022-08-20 13:28 UTC, Hyeondoonge commented
맞아요.. 이메일 하나로 통합 로그인하는 거랑 이메일이 추가 삭제 되는 거까지 생각하니까 너무 복잡하더라구요...ㅠㅠ
provider name, provider id을 사용해서 이 두 값으로 사용자를 식별하는 게 훨씬 쉬워보이네요!!

2022-08-20 14:47 UTC, sangrimlee approved these changes
너무 고생많으셨어요 👍🏼 
주말인데 쉬엄쉬엄하세요 😄

2022-08-20 14:47 UTC, sangrimlee commented on server/src/auth/auth.service.ts
> +    const user = await this.userService.findUserDetailByEmail(email);
UsersService로 다 분리하니깐 전 오히려 더 좋아보이네요 👍🏼

2022-08-20 14:47 UTC, sangrimlee commented on server/src/auth/auth.controller.ts
> +  @Get('/github/sign-in-url')
찾아보니깐 passport는 
로그인 URL을 `/github` 리다이렉트 URL을 `/github/callback`으로 하더라구요!
이걸 한 번 따라가 보는 건 어떨까요?

2022-08-20 14:47 UTC, sangrimlee commented on server/src/config/env.validation.ts
> +  REDIRECT_URL: string;
REDIRECT_URL은 GITHUB를 안 붙인 이유가 있을까요?

다른 OAuth랑 REDIRECT URL도 다 다를 것 같아요!

2022-08-20 14:48 UTC, sangrimlee commented on server/src/auth/auth.service.ts
> +      const response = await fetch(`https://api.github.com/user`, {
네 나중에 OAuthModule로 분리하게되는 Refactoring 작업을 하게 된다면 그때 해도 좋을 것 같아요!

2022-08-20 14:49 UTC, sangrimlee commented on server/src/auth/auth.module.ts
> +    forwardRef(() => UsersModule),
어려워요... DI 어려워요 ㅠㅠ

하지만, 작업해주신 것들을 보니깐 좋아요보여요!

2022-08-20 17:03 UTC, Hyeondoonge commented on server/src/config/env.validation.ts
> +  REDIRECT_URL: string;
그러네요! 수정할게요

2022-08-20 17:15 UTC, Hyeondoonge commented on server/src/auth/auth.controller.ts
> +  @Get('/github/sign-in-url')
좋습니다 변경할게요~!

2022-08-20 23:29 UTC, sangrimlee approved these changes

2022-08-20 23:29 UTC, sangrimlee commented on server/src/config/env.validation.ts
> +  @IsString()
이 부분도 변수명 수정해주셔야할 것 같아요!

2022-08-20 23:29 UTC, sangrimlee commented on server/src/auth/auth.controller.ts
> +  @Get('/github/callback')
이 부분이 제가 설명을 쉽게 못한 것 같아요.

passport의 경우에
Github로그인 요청을 보내는 URL이 `/auth/github`이고

Redirect URL로 지정하는 URL이 `/auth/github/callback`입니다.

한 번 참고해보시라고 링크 남겨놓을게요.

**Reference**
[passport-github2](https://www.passportjs.org/packages/passport-github2/)

2022-08-21 01:24 UTC, Hyeondoonge commented on server/src/config/env.validation.ts
> +  @IsString()
넵!!!

2022-08-21 01:32 UTC, Hyeondoonge commented on server/src/auth/auth.controller.ts
> +  @Get('/github/callback')
아하~ 이해했습니다! callback이 깃허브 인증 후에 부르는 url을 말하는 거였군요!
수정할게요

2022-08-21 01:38 UTC, merged